### ISSUE TITLE
Create gcode from Maker.js

### ISSUE THREAD

**Issue by danmarshall** [oneislandearth/gcode#1]
Hello, this is a really cool project!

I just wanted to leave a note here that some folks have been wanting [Maker.js](https://github.com/microsoft/maker.js) to output gcode. 
https://github.com/microsoft/maker.js/issues/423

It seems out of scope for Maker.js, but perhaps there can be a bridge to/from this library.

**Comment by danzlarkin** [comment]
Hey Dan,

Glad you like our project, we've got much more to do (particularly busy with our 3D mesh library at the moment).

We'll definitely scope out ways of working with Maker.js in the future when possible.

Thanks for sharing our project around and making us aware of this :)
